// States actions
export const FETCH_STATES_REQUEST = 'FETCH_STATES_REQUEST';
export const FETCH_STATES_SUCCESS = 'FETCH_STATES_SUCCESS';
export const FETCH_STATES_FAILURE = 'FETCH_STATES_FAILURE';
export const SET_SELECTED_STATE = 'SET_SELECTED_STATE';

// Shelters actions
export const FETCH_SHELTERS_REQUEST = 'FETCH_SHELTERS_REQUEST';
export const FETCH_SHELTERS_SUCCESS = 'FETCH_SHELTERS_SUCCESS';
export const FETCH_SHELTERS_FAILURE = 'FETCH_SHELTERS_FAILURE';
export const FETCH_SHELTER_DETAIL_REQUEST = 'FETCH_SHELTER_DETAIL_REQUEST';
export const FETCH_SHELTER_DETAIL_SUCCESS = 'FETCH_SHELTER_DETAIL_SUCCESS';
export const FETCH_SHELTER_DETAIL_FAILURE = 'FETCH_SHELTER_DETAIL_FAILURE';
export const SEARCH_SHELTER_BY_MILEAGE_REQUEST = 'SEARCH_SHELTER_BY_MILEAGE_REQUEST';
export const SEARCH_SHELTER_BY_MILEAGE_SUCCESS = 'SEARCH_SHELTER_BY_MILEAGE_SUCCESS';
export const SEARCH_SHELTER_BY_MILEAGE_FAILURE = 'SEARCH_SHELTER_BY_MILEAGE_FAILURE';
export const SEARCH_NEAREST_SHELTERS_REQUEST = 'SEARCH_NEAREST_SHELTERS_REQUEST';
export const SEARCH_NEAREST_SHELTERS_SUCCESS = 'SEARCH_NEAREST_SHELTERS_SUCCESS';
export const SEARCH_NEAREST_SHELTERS_FAILURE = 'SEARCH_NEAREST_SHELTERS_FAILURE';
export const SET_SELECTED_SHELTER = 'SET_SELECTED_SHELTER';
export const CLEAR_SELECTED_SHELTER = 'CLEAR_SELECTED_SHELTER';

// Settings actions
export const SET_UNIT_TYPE = 'SET_UNIT_TYPE';
export const SET_THEME_TYPE = 'SET_THEME_TYPE';

// Cache actions
export const LOAD_CACHE_REQUEST = 'LOAD_CACHE_REQUEST';
export const LOAD_CACHE_SUCCESS = 'LOAD_CACHE_SUCCESS';
export const LOAD_CACHE_FAILURE = 'LOAD_CACHE_FAILURE';
export const SAVE_CACHE_REQUEST = 'SAVE_CACHE_REQUEST';
export const SAVE_CACHE_SUCCESS = 'SAVE_CACHE_SUCCESS';
export const SAVE_CACHE_FAILURE = 'SAVE_CACHE_FAILURE';
export const CLEAR_CACHE_REQUEST = 'CLEAR_CACHE_REQUEST';
export const CLEAR_CACHE_SUCCESS = 'CLEAR_CACHE_SUCCESS';
export const CLEAR_CACHE_FAILURE = 'CLEAR_CACHE_FAILURE'; 